# Generated by Django 2.0.2 on 2018-02-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField(choices=[('Calamina', 'Calamina')], verbose_name='Material')),
                ('descripcion', models.TextField(verbose_name='Descripcion Pedido')),
                ('cantidad', models.IntegerField()),
                ('costo_u', models.FloatField(default=0, verbose_name='Costo Unitario')),
                ('costo_t', models.FloatField(verbose_name='Costo Total')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles Pedidos',
                'ordering': ['pedido', 'material'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('costo', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['fecha', 'cliente'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido'),
        ),
    ]
