# Generated by Django 2.0.2 on 2018-02-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='venta',
            field=models.BooleanField(default=False),
        ),
    ]
