# Generated by Django 2.0.3 on 2018-04-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0014_auto_20180401_2104'),
        ('pedidos', '0003_auto_20180307_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['pedido', 'tmaterial'], 'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalles Pedidos'},
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='tmaterial',
            field=models.TextField(choices=[('Calamina', 'Calamina'), ('Clavos', 'Clavos')], null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='costo_t',
            field=models.FloatField(help_text='En Bolivianos', verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='costo_u',
            field=models.FloatField(default=0, help_text='En Bolivianos', verbose_name='Costo Unitario'),
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='material',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='material',
            field=models.ManyToManyField(null=True, to='materiales.MateriaPrima'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='unidad',
            field=models.CharField(choices=[('Pieza', 'Pieza'), ('Kilos', 'Kilos')], default='Unidad', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
