# Generated by Django 2.0.3 on 2018-04-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20180401_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='material',
            field=models.ManyToManyField(to='materiales.MateriaPrima'),
        ),
    ]
