# Generated by Django 2.0.3 on 2018-04-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20180401_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['pedido'], 'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalles Pedidos'},
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='tmaterial',
        ),
    ]
