# Generated by Django 2.0.3 on 2018-04-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20180401_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='largo',
            field=models.FloatField(null=True),
        ),
    ]
