# Generated by Django 2.0.3 on 2018-04-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_detallepedido_largo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='ancho',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='totalm',
            field=models.FloatField(null=True),
        ),
    ]
