# Generated by Django 2.0.3 on 2018-04-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20180401_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plazo',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
