# Generated by Django 2.0.3 on 2018-04-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20180401_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(help_text='Direccion', max_length=300, null=True, verbose_name='Lugar de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plazo',
            field=models.IntegerField(default=1, help_text='En Dias', verbose_name='Plazo de Entrega'),
        ),
    ]
