# Generated by Django 2.0.2 on 2018-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20180401_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='ancho',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
