# Generated by Django 2.0.3 on 2018-04-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20180401_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nro_pedido',
            field=models.IntegerField(null=True),
        ),
    ]
