# Generated by Django 2.0.3 on 2018-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_nro_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
