# Generated by Django 2.0.3 on 2018-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_detallepedido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='persona_entrega',
            field=models.CharField(help_text='Persona de referencia para entrega', max_length=100, null=True, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_ref',
            field=models.IntegerField(null=True, verbose_name='Telefono Persona Referencia'),
        ),
    ]
