# Generated by Django 2.0.2 on 2018-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
    ]
