# Generated by Django 2.0.2 on 2018-02-04 19:20

import clientes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['pais', 'ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10, unique=True, validators=[clientes.models.validate_ci], verbose_name='Cedula de Identidad')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono/Ceular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Ciudad', verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paices',
                'ordering': ['pais'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Pais'),
        ),
    ]
