# Generated by Django 2.0.3 on 2018-04-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=20, null=True, verbose_name='NIT'),
        ),
    ]
