# Generated by Django 2.0.3 on 2018-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='razon',
            field=models.CharField(max_length=100, null=True, verbose_name='Razon Social'),
        ),
    ]
