# Generated by Django 2.0.3 on 2018-06-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20180422_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre o Razon Social'),
        ),
    ]
