# Generated by Django 2.0.2 on 2018-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20180623_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais',
            field=models.CharField(max_length=30, unique=True, verbose_name='País'),
        ),
    ]
