# Generated by Django 2.0.2 on 2018-08-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20180816_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
    ]
