# Generated by Django 2.0.3 on 2018-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(verbose_name='NIT Empresa')),
                ('nro', models.IntegerField(verbose_name='Numero de Autorizacion')),
                ('key', models.CharField(max_length=500, verbose_name='Llave de Dosificacion')),
            ],
        ),
    ]
