# Generated by Django 2.0.3 on 2018-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=50)),
                ('hexa', models.CharField(max_length=20)),
            ],
        ),
    ]
