# Generated by Django 2.0.3 on 2018-06-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_colorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
