# Generated by Django 2.0.3 on 2018-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180623_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='vencimiento',
            field=models.DateField(null=True),
        ),
    ]
