# Generated by Django 2.0.3 on 2018-07-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_empresa_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sms',
            field=models.TextField(max_length=500, null=True, verbose_name='Mensaje de Factura'),
        ),
    ]
