# Generated by Django 2.0.3 on 2018-04-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20180307_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nro_venta',
            field=models.IntegerField(null=True),
        ),
    ]
