# Generated by Django 2.0.3 on 2018-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_nro_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_id',
            field=models.IntegerField(null=True),
        ),
    ]
