# Generated by Django 2.0.3 on 2018-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_largo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
