# Generated by Django 2.0.3 on 2018-06-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0033_auto_20180601_0128'),
        ('ventas', '0006_detalleventa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='materia_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.MateriaPrima'),
        ),
    ]
