# Generated by Django 2.0.3 on 2018-08-14 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0039_auto_20180813_2128'),
        ('ventas', '0007_detalleventa_materia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='preciocalamina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.PrecioCalamina'),
        ),
    ]
