# Generated by Django 2.0.3 on 2018-08-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0039_auto_20180813_2128'),
        ('ventas', '0008_detalleventa_preciocalamina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['venta', 'preciocalamina'], 'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalle Ventas'},
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='materia_id',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='material',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='material',
            field=models.ManyToManyField(to='materiales.MateriaPrima'),
        ),
    ]
