# Generated by Django 2.0.3 on 2018-08-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20180813_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='totalm',
            field=models.FloatField(null=True),
        ),
    ]
