# Generated by Django 2.0.2 on 2018-08-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_detalleventa_totalm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='material',
            field=models.ManyToManyField(choices=[('Calamina', 'Calamina'), ('Clavos', 'Clavos')], to='materiales.MateriaPrima'),
        ),
    ]
