# Generated by Django 2.0.2 on 2018-08-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20180816_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='unidad',
            field=models.CharField(choices=[('Kilos', 'Kilos')], default='Kilos', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
