# Generated by Django 2.0.2 on 2018-08-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0042_auto_20180828_0908'),
        ('ventas', '0015_auto_20180828_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precioclavos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.PrecioClavos'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='unidad',
            field=models.CharField(choices=[('Kilos', 'Kilos'), ('Calamina', 'Calamina')], default='Kilos', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
