# Generated by Django 2.0.2 on 2018-02-05 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca Producto')),
                ('espesor', models.IntegerField(help_text='En Milimetros (mm)', verbose_name='Espesor')),
                ('ancho', models.IntegerField(help_text='En Milimetros (mm)', verbose_name='Ancho')),
                ('superficie', models.CharField(max_length=150, verbose_name='Tratamiento de Superficie')),
                ('estandar', models.CharField(max_length=150, verbose_name='Estandares')),
                ('certificacion', models.CharField(max_length=150, verbose_name='Certificaciones')),
                ('peso', models.IntegerField(help_text='En Toneladas (TM)', verbose_name='Peso')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materia Prima Calamina',
                'verbose_name_plural': 'Materia Prima Calaminas',
                'ordering': ['fecha'],
            },
        ),
    ]
