# Generated by Django 2.0.2 on 2018-02-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
