# Generated by Django 2.0.2 on 2018-02-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_auto_20180220_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
