# Generated by Django 2.0.3 on 2018-03-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_auto_20180331_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad',
            field=models.IntegerField(default='1', verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='medida',
            field=models.CharField(choices=[('Kilos', 'Kilos')], max_length=100, null=True, verbose_name='Tipo de Medida'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad',
            field=models.CharField(default='Bobina', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
