# Generated by Django 2.0.3 on 2018-04-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_materiaprima_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('precio', models.FloatField(help_text='En Bolivianos', verbose_name='Precio Metro L.')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tabla de Precio',
                'verbose_name_plural': 'Tabla de Precios',
                'ordering': ['precio'],
            },
        ),
    ]
