# Generated by Django 2.0.3 on 2018-04-01 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0010_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.Precio'),
        ),
    ]
