# Generated by Django 2.0.3 on 2018-04-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0011_materiaprima_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='precio',
        ),
    ]
