# Generated by Django 2.0.3 on 2018-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0012_remove_materiaprima_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='ancho',
            field=models.FloatField(help_text='En Milimetros (mm)', verbose_name='Ancho'),
        ),
    ]
