# Generated by Django 2.0.3 on 2018-04-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_razon'),
        ('materiales', '0015_auto_20180401_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Ciudad', verbose_name='Ciudad de origen'),
        ),
    ]
