# Generated by Django 2.0.2 on 2018-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0015_auto_20180401_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='espesor',
            field=models.FloatField(help_text='En Milimetros (mm)', verbose_name='Espesor'),
        ),
    ]
