# Generated by Django 2.0.2 on 2018-04-02 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0016_auto_20180402_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='ancho',
            field=models.FloatField(help_text='En Metros Lineales (ml)', null=True, verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='certificacion',
            field=models.CharField(max_length=150, null=True, verbose_name='Certificaciones'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='espesor',
            field=models.FloatField(help_text='En Milimetros (mm)', null=True, verbose_name='Espesor'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='estandar',
            field=models.CharField(max_length=150, null=True, verbose_name='Estandares'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='marca',
            field=models.CharField(max_length=100, null=True, verbose_name='Marca Producto'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='peso',
            field=models.IntegerField(null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='salida',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='superficie',
            field=models.CharField(max_length=150, null=True, verbose_name='Tratamiento de Superficie'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
