# Generated by Django 2.0.3 on 2018-04-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0016_proveedor_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='certificacion',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='estandar',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='superficie',
        ),
    ]
