# Generated by Django 2.0.3 on 2018-04-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0017_auto_20180415_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='color',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Naranja', 'Naranja'), ('Verde', 'Verde')], default='Sin Color', max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='precio',
            name='espesor',
            field=models.IntegerField(help_text='En Milimetros (mm)', null=True, verbose_name='Espesor'),
        ),
    ]
