# Generated by Django 2.0.3 on 2018-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0019_auto_20180415_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='tipo',
            field=models.CharField(choices=[('Calamina', 'Calamina'), ('Clavos', 'Clavos')], default='Calamina', max_length=10, verbose_name='Tipo Material'),
        ),
    ]
