# Generated by Django 2.0.3 on 2018-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0020_materiaprima_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='ancho',
            field=models.FloatField(blank=True, help_text='En Metros Lineales (ml)', null=True, verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='longitud',
            field=models.IntegerField(blank=True, help_text='En Metros Lineales', null=True, verbose_name='Longitud Aproximada'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad',
            field=models.CharField(choices=[('Bobina', 'Bobina'), ('Alambron', 'Alambron')], default='Bobina', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
