# Generated by Django 2.0.3 on 2018-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0021_auto_20180422_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='color',
            field=models.CharField(blank=True, choices=[('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Naranja', 'Naranja'), ('Verde', 'Verde')], default='Sin Color', max_length=100, null=True, verbose_name='Color'),
        ),
    ]
