# Generated by Django 2.0.3 on 2018-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0022_auto_20180422_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='color',
            field=models.CharField(blank=True, default='Sin Color', max_length=100, null=True, verbose_name='Color'),
        ),
    ]
