# Generated by Django 2.0.3 on 2018-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0023_auto_20180423_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='longitud',
            field=models.IntegerField(blank=True, default=0, help_text='En Metros Lineales', null=True, verbose_name='Longitud Aproximada'),
        ),
    ]
