# Generated by Django 2.0.3 on 2018-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0024_auto_20180423_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='ancho',
            field=models.FloatField(blank=True, default=0, help_text='En Metros Lineales (ml)', null=True, verbose_name='Ancho'),
        ),
    ]
