# Generated by Django 2.0.3 on 2018-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0025_auto_20180423_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioClavos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('precio', models.FloatField(help_text='En Bolivianos', verbose_name='Precio Kilo.')),
                ('longitud', models.FloatField(help_text='En Milimetros (mm)', null=True, verbose_name='Longitud')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tabla de Precio Clavo',
                'verbose_name_plural': 'Tabla de Precios Clavos',
                'ordering': ['precio'],
            },
        ),
    ]
