# Generated by Django 2.0.3 on 2018-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0027_precioclavos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioclavos',
            name='stock',
            field=models.IntegerField(default=1, help_text='En Kilos'),
        ),
    ]
