# Generated by Django 2.0.3 on 2018-05-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0030_auto_20180513_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='precioc',
            field=models.FloatField(default=0, verbose_name='Precio de Compra'),
        ),
    ]
