# Generated by Django 2.0.2 on 2018-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0030_auto_20180513_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='codigo',
            field=models.CharField(max_length=11, verbose_name='Codigo'),
        ),
    ]
