# Generated by Django 2.0.3 on 2018-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0031_materiaprima_precioc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='precioc',
            field=models.FloatField(default=0, help_text='En Bolivianos', verbose_name='Precio de Compra'),
        ),
    ]
