# Generated by Django 2.0.2 on 2018-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0031_auto_20180514_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='codigob',
            field=models.CharField(default=1, max_length=11, verbose_name='Codigo Bobina'),
            preserve_default=False,
        ),
    ]
