# Generated by Django 2.0.2 on 2018-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0032_auto_20180516_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='color',
            field=models.CharField(default='Sin Color', max_length=100, null=True, verbose_name='Color'),
        ),
    ]
