# Generated by Django 2.0.2 on 2018-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0032_precio_codigob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='codigob',
            field=models.CharField(max_length=11, verbose_name='Serie'),
        ),
    ]
