# Generated by Django 2.0.2 on 2018-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0033_auto_20180514_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='codigob',
        ),
        migrations.AddField(
            model_name='precio',
            name='serie',
            field=models.CharField(max_length=100, null=True, verbose_name='Serie'),
        ),
    ]
