# Generated by Django 2.0.3 on 2018-06-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0033_auto_20180601_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='codigo',
            field=models.CharField(help_text='Codigo de tipo de Calamina', max_length=10, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='descripcion',
            field=models.CharField(help_text='Pequeña descripción', max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='materia',
            field=models.ForeignKey(help_text='Materia Prima', null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.MateriaPrima'),
        ),
    ]
