# Generated by Django 2.0.2 on 2018-05-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0034_auto_20180514_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='precio_m',
            field=models.FloatField(default=1, help_text='En Bolivianos', verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
