# Generated by Django 2.0.2 on 2018-05-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0035_materiaprima_precio_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='serie',
        ),
    ]
