# Generated by Django 2.0.3 on 2018-07-26 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0036_auto_20180725_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciocalamina',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.CodigoCalamina'),
        ),
        migrations.AlterField(
            model_name='preciocalamina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.TipoCalamina'),
        ),
    ]
