# Generated by Django 2.0.3 on 2018-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0037_auto_20180725_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigocalamina',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo De Calamina'),
        ),
    ]
