# Generated by Django 2.0.3 on 2018-08-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0038_auto_20180726_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciocalamina',
            name='nro_codigo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
