# Generated by Django 2.0.3 on 2018-08-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0039_auto_20180813_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoMateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo Materia Prima')),
            ],
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.CodigoMateriaPrima'),
        ),
    ]
