# Generated by Django 2.0.2 on 2018-08-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0040_auto_20180813_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoClavo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo De Clavo')),
            ],
        ),
        migrations.AlterField(
            model_name='precioclavos',
            name='codigo',
            field=models.ForeignKey(on_delete=models.Model, to='materiales.CodigoClavo'),
        ),
    ]
