# Generated by Django 2.0.2 on 2018-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0041_auto_20180816_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocalamina',
            name='tipo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo De Calamina'),
        ),
    ]
