# Generated by Django 2.0.2 on 2018-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0042_auto_20180828_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigomateriaprima',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
