# Generated by Django 2.0.2 on 2018-09-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0043_codigomateriaprima_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigomateriaprima',
            name='estado',
        ),
    ]
